version: '3.7'

services:
  gatsby:
    build:
      context: ./docker
      dockerfile: gatsby.Dockerfile
    entrypoint: gatsby
    volumes:
      - .:/app

  develop:
    build:
      context: ./docker
      dockerfile: gatsby.Dockerfile
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app